# o - organization（组织-公司）
# ou - organization unit（组织单元-部门）
# c - countryName（国家）
# dc - domainComponent（域名）
# sn - suer name（真实名称）
# cn - common name（常用名称

spring:
  ldap:
    urls: ldap://ldap.xinc818.com:389
    base: dc=xincheng,dc=org
    username: 'cn=openldap,dc=xincheng,dc=org'
    password: ENC(qq58+/rxv7G6AVgzQsbDOvJ4ZurhVOv4)


ldap:
  custom:  {userId: cn,
            userBaseDN: ou=Group,
            userObjectClass: inetOrgPerson,
            groupId: cn,
            groupBaseDN: ou=Group,
            groupObjectClass: groupOfUniqueNames,
            groupMember: uniqueMember}